### ISSUE TITLE
Add library info

### ISSUE THREAD

**Issue by nikita-sheremet-java-developer** [speedwing/log4j-cloudwatch-appender#5]
1. What is logf4j version is supported? I can not compile `Logger.getRootLogger().addAppender(cloudwatchAppender);` with log4j 2.7
1. What is your library version??? pom.xml says 0.0.6-SNAPSHOT, maven repository tells 0.0.2. What is last or where are 3,4 and 5 versions?

**Comment by nemo83** [comment]
* Log4j 2.x is not supported. Latest supported version is `1.2.17` as per  [pom.xml](https://github.com/speedwing/log4j-cloudwatch-appender/blob/master/pom.xml#L52)
* Release of versions 3 and 4 failed because of artifact signature... but not sure about what happened with version 5... it should be on maven central by now... :-(

**Comment by nemo83** [comment]
version [0.0.3](http://search.maven.org/#artifactdetails%7Ccom.github.speedwing%7Clog4j-cloudwatch-appender%7C0.0.3%7Cjar) is now out.
